#!/bin/bash

# For use on Gradescope
# See https://gradescope-autograders.readthedocs.io

cd /autograder/
mkdir -p source/workshops/workshop/submissions/
cp -r submission source/workshops/workshop/submissions/
cd source/
npm run gradescope
mkdir -p /autograder/results/
node ./workshops/modify-results.js
