#!/bin/bash

# For use on Gradescope
# See https://gradescope-autograders.readthedocs.io

cd /autograder/
mkdir -p source/workshops/workshop/submissions/
cp -r submission source/workshops/workshop/submissions/
cd source/
npm run gradescope
node workshops/modify-results.js
mkdir -p /autograder/results/
ln -s /autograder/source/workshops/results.json /autograder/results/results.json
